hydra:
  searchpath:
    - file://verl/trainer/config
defaults:
  - base
  - _self_
data:
  train_files:
    - new_version/data/composition/heldout/op18-137500.jsonl
    - new_version/data/composition/heldout/op19-137500.jsonl
    - new_version/data/composition/heldout/op20-137500.jsonl
trainer:
  experiment_name: uniform-op18-20
